### ISSUE TITLE
ImportError: No module named numarray.util

### ISSUE THREAD

**Issue by heliy** [jamesra/nornir-buildmanager#1]
I installed nornir and met this error when I try to run the 'nornir-build' command:

```
  File "/usr/local/lib/python2.7/dist-packages/nornir_imageregistration/arrange_mosaic.py", line 24, in <module>
    from numpy.numarray.util import UnderflowError
ImportError: No module named numarray.util
```
It shows that 'numarray' module have been removed since [NumPy 1.9.0.](https://docs.scipy.org/doc/numpy/reference/routines.numarray.html).

But the required dependencies of this package is `numpy>=1.9.1`

Both Linux & Windows system have this error.

Is there any specific version of numpy helpful?

**Comment by jamesra** [comment]
That is odd.  I checked the build server at our lab.  “pip list” shows us running numpy (1.11.3+mkl).  For Windows we download the MKL build of numpy from Christopher Gohlke’s site: https://www.lfd.uci.edu/~gohlke/pythonlibs/

The underflow exception is used in a very limited way.  I will look into what module that exception has been moved to.

**Comment by jamesra** [comment]
I am sorry.  It appears changes to my master branch have not been pushed to the official Nornir site.  The version we are using does not use that underflow exception which is why we don’t see the error.  I will review the differences and then update the official nornir version.

**Comment by jamesra** [comment]
I've updated the official Nornir release with the latest source code.  Please let me know if this fixes the issue.

**Comment by heliy** [comment]
Thank you so much! It works well. :)
